project:
  type: website
  output-dir: docs
  render:
  - '*.qmd'

website:
  title: 'beeR'
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: litera
    css: styles.css
    toc: true



