project:
  type: website
  output-dir: docs
  render:
  - '*.qmd'

website:
  title: 'beeR'
  navbar:
    pinned: true
    left:
      - text: Home
        href: index.qmd
    right:
      - about.qmd
      - text: Tutorials
        href: tutorials/index.qmd

format:
  html:
    theme: litera
    css: styles.css
    toc: true



